name: folio
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.0
  http: ^0.13.4
  dio: ^4.0.4
  image_picker: ^0.8.4+11
  dropdown_button2: ^1.2.2
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  get:

dev_dependencies:
  flutter_native_splash: ^2.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/example/
    - assets/icon/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/pretendard/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/font/pretendard/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/font/pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/font/pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/font/pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/font/pretendard/Pretendard-Semibold.ttf
          weight: 600
        - asset: assets/font/pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/font/pretendard/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/font/pretendard/Pretendard-Black.ttf
          weight: 900